### ISSUE TITLE
error: unresolved name `netmap::nm_open`

### ISSUE THREAD

**Issue by larseggert** [libpnet/netmap_sys#2]
OK, next issue. I may be too much of a rust newbie here; feel free to tell me.

My `main.rs` is simply:

```
extern crate "rust-netmap" as netmap;

fn main() {
    println!("Hello, world!");

    let n = netmap::nm_open("eth1", 0, 0, 0);
}
```

`cargo build` fails with

```
[lars@tux: ~/rustcore] cargo build -v
       Fresh rust-netmap v0.0.4 (https://github.com/libpnet/rust-netmap.git#ab947ee2)
   Compiling rustcore v0.0.1 (file:///mnt/home/vmhome/rustcore)
     Running `rustc src/main.rs --crate-name rustcore --crate-type bin -g --out-dir /mnt/home/vmhome/rustcore/target --emit=dep-info,link -L dependency=/mnt/home/vmhome/rustcore/target -L dependency=/mnt/home/vmhome/rustcore/target/deps --extern rust-netmap=/mnt/home/vmhome/rustcore/target/deps/librust-netmap-10a85511dfe14665.so --extern rust-netmap=/mnt/home/vmhome/rustcore/target/deps/librust-netmap-10a85511dfe14665.rlib -L native=/mnt/home/vmhome/rustcore/target/build/rust-netmap-10a85511dfe14665/out`
src/main.rs:6:10: 6:25 error: unresolved name `netmap::nm_open`
src/main.rs:6   let n = netmap::nm_open("eth1", 0, 0, 0);
                        ^~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rustcore`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name rustcore --crate-type bin -g --out-dir /mnt/home/vmhome/rustcore/target --emit=dep-info,link -L dependency=/mnt/home/vmhome/rustcore/target -L dependency=/mnt/home/vmhome/rustcore/target/deps --extern rust-netmap=/mnt/home/vmhome/rustcore/target/deps/librust-netmap-10a85511dfe14665.so --extern rust-netmap=/mnt/home/vmhome/rustcore/target/deps/librust-netmap-10a85511dfe14665.rlib -L native=/mnt/home/vmhome/rustcore/target/build/rust-netmap-10a85511dfe14665/out` (exit code: 101)
```

I do have `features = ["netmap_with_libs"]` in my `Cargo.toml`, per your README. What am I missing?

**Comment by mrmonday** [comment]
I've just run through getting this working myself, here's my src/main.rs file:

``` rust
#![feature(std_misc)]
extern crate "rust-netmap" as netmap;

use netmap::netmap_user;

use std::ffi::CString;
use std::ptr;

fn main() {
    println!("Hello, world!");

    let iface_name = CString::new(b"eth1").unwrap();
    unsafe {
        let n = netmap_user::nm_open(iface_name.as_ptr(), ptr::null(), 0, ptr::null());
    }
}
```

and my Cargo.toml:

``` toml
[package]

name = "test-project"
version = "0.0.1"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]

[dependencies.rust-netmap]
git = "https://github.com/libpnet/rust-netmap.git"
# Uncomment this line where you wish to use features guarded by the
# NETMAP_WITH_LIBS macro in C.
features = ["netmap_with_libs"]
```

I'm going to close the issue, but feel free to ask more questions :)
